[tool.black]
line-length = 120
target-version = ["py310"]

[tool.ruff]
line-length = 120
src = ["backend", "scripts"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "ANN", "ASYNC", "S", "N", "W"]
ignore = ["ANN101", "ANN102", "ANN401", "S311"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
