name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
          python -m pip install pre-commit
      - name: Verify renderer schema
        run: |
          python - <<'PY'
          from pathlib import Path
          schema = Path('backend/schemas/render_manifest.schema.json')
          if not schema.exists():
              raise SystemExit('schema missing')
          import backend.renderer as renderer
          print('VideoComposer ready:', renderer.VideoComposer.__name__)
          print('Schema size:', schema.stat().st_size)
          PY
      - name: Compile backend
        run: python -m compileall backend
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
